### ISSUE TITLE
About NED Frame Z Axis

### ISSUE THREAD

**Issue by imcuriousengineer** [JSBSim-Team/jsbsim-reference-manual#38]
Hello.

In the [North-Oriented Tangent Frames](https://jsbsim-team.github.io/jsbsim-reference-manual/user/concepts/frames-of-reference/#north-oriented-tangent-frames) section, the document says "The axis XE points towards the geographic North, the axis YE points towards the East. Finally, the axis ZE points downwards towards the center of the Earth.".

![image](https://github.com/JSBSim-Team/jsbsim-reference-manual/assets/152016173/1bcd4754-3188-40d3-b066-60034b7051ec)

Because WGS84 has been implemented after the issue https://github.com/JSBSim-Team/jsbsim/issues/184, I think the Z axis is no longer pointing to the center of the Earth anymore (unless someone gives the same length to the `semimajor_axis` and `semiminor_axis` using `<planet>`).

Here is a part of the doc comment for the `FGLocation` class: "The X-axis points towards north, the Y-axis points east and the Z-axis is normal to the reference spheroid (WGS84 for Earth)."

**Comment by agodemar** [comment]
@imcuriousengineer thanks for pointing out the issue. How would you rephrase the wrong sentence?

**Comment by seanmcleod** [comment]
From - https://github.com/JSBSim-Team/jsbsim/issues/184#issuecomment-680221651

In Stevens & Lewis *"Aircraft Control and Simulation - 3rd edition"*, it is specified that the NED frame transformation matrix should be computed with the geodetic latitude so that the down axis be parallel to the spheroid normal (p. 27 for the principles and p. 31 for the formula 1.6-22 of the transformation matrix). They also explain that the gravity computed with the J2 formula (and taking into account the centripetal acceleration) is parallel to the spheroid normal within a few micro-g's (p.33).

**Comment by imcuriousengineer** [comment]
@agodemar thanks for the quick reply.

I'm not sure, maybe like this?
> Finally, the axis ZE points downwards, parallel to the spheroid normal (It points to the center of the Earth if an approximating sphere is used instead of a spheroid)

**Comment by agodemar** [comment]
The orientation and direction of axis $z_E$ within an *Earth-tangent* NED frame $\mathcal{F}_E = \\{O_E, x_E, y_E, z_E\\}$ are now more precisely described in section [North-Oriented Tangent Frames of the online reference manual](https://jsbsim-team.github.io/jsbsim-reference-manual/user/concepts/frames-of-reference/#north-oriented-tangent-frames).

**Comment by imcuriousengineer** [comment]
@agodemar Great, thanks!
